##Import Libraries

In [1]:
import pandas as pd
import numpy as np

## Data load

In [2]:
df = pd.read_csv('/content/drive/My Drive/machine learning/classification/data/Human_Resources_Employee_Attrition.csv')
df.describe()

satisfaction_level  last_evaluation  ...          left  promotion_last_5years
count        14999.000000     14999.000000  ...  14999.000000           14999.000000
mean             0.612834         0.716102  ...      0.238083               0.021268
std              0.248631         0.171169  ...      0.425924               0.144281
min              0.090000         0.360000  ...      0.000000               0.000000
25%              0.440000         0.560000  ...      0.000000               0.000000
50%              0.640000         0.720000  ...      0.000000               0.000000
75%              0.820000         0.870000  ...      0.000000               0.000000
max              1.000000         1.000000  ...      1.000000               1.000000

[8 rows x 8 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   satisfaction_level     14999 non-null  float64
 1   last_evaluation        14999 non-null  float64
 2   number_of_projects     14999 non-null  int64  
 3   average_monthly_hours  14999 non-null  int64  
 4   years_at_company       14999 non-null  int64  
 5   work_accident          14999 non-null  int64  
 6   left                   14999 non-null  int64  
 7   promotion_last_5years  14999 non-null  int64  
 8   department             14999 non-null  object 
 9   salary                 14999 non-null  object 
dtypes: float64(2), int64(6), object(2)
memory usage: 1.1+ MB


In [4]:
df.salary.unique()

array(['low', 'medium', 'high'], dtype=object)

In [5]:
df.salary.unique()

array(['low', 'medium', 'high'], dtype=object)

In [6]:
df.salary.value_counts(ascending=False)

low       7316
medium    6446
high      1237
Name: salary, dtype: int64

In [7]:
df.department.unique()

array(['sales', 'accounting', 'hr', 'technical', 'support', 'management',
       'IT', 'product_mng', 'marketing', 'RandD'], dtype=object)

In [8]:
df.department.value_counts()

sales          4140
technical      2720
support        2229
IT             1227
product_mng     902
marketing       858
RandD           787
accounting      767
hr              739
management      630
Name: department, dtype: int64

In [9]:
df1 = df.copy()

## we have to change the categorcial data  into num data

### LabelEncoder

In [10]:
# in the target column we apply Lablencoding
# feature column we use OneHotEncoding

In [11]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [12]:
df1.iloc[:,9] = encoder.fit_transform(df1.iloc[:,9])

In [13]:
df1.head()

satisfaction_level  last_evaluation  ...  department  salary
0                0.38             0.53  ...       sales       1
1                0.80             0.86  ...       sales       2
2                0.11             0.88  ...       sales       2
3                0.72             0.87  ...       sales       1
4                0.37             0.52  ...       sales       1

[5 rows x 10 columns]

In [14]:
df.head()

satisfaction_level  last_evaluation  ...  department  salary
0                0.38             0.53  ...       sales     low
1                0.80             0.86  ...       sales  medium
2                0.11             0.88  ...       sales  medium
3                0.72             0.87  ...       sales     low
4                0.37             0.52  ...       sales     low

[5 rows x 10 columns]

In [15]:
df1.salary.unique()

array([1, 2, 0])

In [16]:
encoder.classes_
# high 0 ,low 1 ,medium 2

array(['high', 'low', 'medium'], dtype=object)

In [17]:
df.shape

(14999, 10)

###OneHotEncoding

In [18]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(dtype='int64')

In [19]:
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers = [('encoding',onehotencoder,[8])],remainder = 'passthrough')

In [20]:
df2 = ct.fit_transform(df1.iloc[:,:9])

In [21]:
df2.shape

(14999, 18)

In [22]:
df2.dtype

dtype('float64')

In [23]:
df2

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [25]:
df2[1]

array([  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   1.  ,
         0.  ,   0.  ,   0.8 ,   0.86,   5.  , 262.  ,   6.  ,   0.  ,
         1.  ,   0.  ])

In [26]:
df2 = pd.DataFrame(df2)

In [27]:
df2.head()

0    1    2    3    4    5    6   ...    11   12     13   14   15   16   17
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.53  2.0  157.0  3.0  0.0  1.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.86  5.0  262.0  6.0  0.0  1.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.88  7.0  272.0  4.0  0.0  1.0  0.0
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.87  5.0  223.0  5.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.52  2.0  159.0  3.0  0.0  1.0  0.0

[5 rows x 18 columns]

In [28]:
df2.head()

0    1    2    3    4    5    6   ...    11   12     13   14   15   16   17
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.53  2.0  157.0  3.0  0.0  1.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.86  5.0  262.0  6.0  0.0  1.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.88  7.0  272.0  4.0  0.0  1.0  0.0
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.87  5.0  223.0  5.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.52  2.0  159.0  3.0  0.0  1.0  0.0

[5 rows x 18 columns]

In [29]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       14999 non-null  float64
 1   1       14999 non-null  float64
 2   2       14999 non-null  float64
 3   3       14999 non-null  float64
 4   4       14999 non-null  float64
 5   5       14999 non-null  float64
 6   6       14999 non-null  float64
 7   7       14999 non-null  float64
 8   8       14999 non-null  float64
 9   9       14999 non-null  float64
 10  10      14999 non-null  float64
 11  11      14999 non-null  float64
 12  12      14999 non-null  float64
 13  13      14999 non-null  float64
 14  14      14999 non-null  float64
 15  15      14999 non-null  float64
 16  16      14999 non-null  float64
 17  17      14999 non-null  float64
dtypes: float64(18)
memory usage: 2.1 MB


## feature and target

In [30]:
X = df2.iloc[:,:-1].values
y = df1['salary'].values

In [31]:
X.shape,y.shape

((14999, 17), (14999,))

## Scale

In [32]:
from sklearn.preprocessing import StandardScaler
std =StandardScaler()
X = std.fit_transform(X)

## train test split data

In [33]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

##Model

In [34]:
from sklearn.tree import DecisionTreeClassifier

In [35]:
tree = DecisionTreeClassifier().fit(X_train,y_train)

In [36]:
y_pred= tree.predict(X_test)

### confusion matrix and classification report

In [37]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 98  88  67]
 [ 82 946 446]
 [ 88 449 736]]
              precision    recall  f1-score   support

           0       0.37      0.39      0.38       253
           1       0.64      0.64      0.64      1474
           2       0.59      0.58      0.58      1273

    accuracy                           0.59      3000
   macro avg       0.53      0.54      0.53      3000
weighted avg       0.59      0.59      0.59      3000



## cross validation score

In [38]:
from sklearn.model_selection import cross_val_score
score = cross_val_score(tree,X,y,cv=10)

In [39]:
score

array([0.69133333, 0.47133333, 0.44      , 0.42466667, 0.42      ,
       0.412     , 0.48466667, 0.93866667, 0.998     , 0.99799867])

In [40]:
score.mean()

0.6278665332443851

## hyperparameter tuning

In [47]:
#The function to measure the quality of a split
criterion = ['gini','entropy']

#The maximum depth of the tree.
max_depth = [int(i) for i in np.linspace(10,1000,10)]

#he minimum number of samples required to split an internal node
min_sample_split = [2,5,10,14]

#The minimum number of samples required to be at a leaf node.
min_samples_leaf = [i for i in range(1,11)]

#The number of features to consider when looking for the best split:
max_features = ['auto', 'sqrt','log2']

In [ ]:
'min_sample_split':min_sample_split,
'min_sample_leaf':min_samples_leaf,

In [53]:
tree = DecisionTreeClassifier(random_state=42)

para_grid = {'criterion': criterion,
             'max_depth':max_depth,
             
             
             'max_features':max_features}


para_grid

{'criterion': ['gini', 'entropy'],
 'max_depth': [10, 120, 230, 340, 450, 560, 670, 780, 890, 1000],
 'max_features': ['auto', 'sqrt', 'log2']}

In [54]:
from sklearn.model_selection import RandomizedSearchCV,GridSearchCV

In [55]:
random_search = RandomizedSearchCV(estimator=tree,param_distributions=para_grid,
                                   n_iter = 100,cv= 3,verbose =2,random_state=42)


random_search.fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:281: UserWarning: The total space of parameters 60 is smaller than n_iter=100. Running 60 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s


Fitting 3 folds for each of 60 candidates, totalling 180 fits
[CV] max_features=auto, max_depth=10, criterion=gini .................
[CV] .. max_features=auto, max_depth=10, criterion=gini, total=   0.0s
[CV] max_features=auto, max_depth=10, criterion=gini .................
[CV] .. max_features=auto, max_depth=10, criterion=gini, total=   0.0s
[CV] max_features=auto, max_depth=10, criterion=gini .................
[CV] .. max_features=auto, max_depth=10, criterion=gini, total=   0.0s
[CV] max_features=sqrt, max_depth=10, criterion=gini .................
[CV] .. max_features=sqrt, max_depth=10, criterion=gini, total=   0.0s
[CV] max_features=sqrt, max_depth=10, criterion=gini .................
[CV] .. max_features=sqrt, max_depth=10, criterion=gini, total=   0.0s
[CV] max_features=sqrt, max_depth=10, criterion=gini .................
[CV] .. max_features=sqrt, max_depth=10, criterion=gini, total=   0.0s
[CV] max_features=log2, max_depth=10, criterion=gini .................
[CV] .. max_fea

[Parallel(n_jobs=1)]: Done 180 out of 180 | elapsed:    3.1s finished


RandomizedSearchCV(cv=3, error_score=nan,
                   estimator=DecisionTreeClassifier(ccp_alpha=0.0,
                                                    class_weight=None,
                                                    criterion='gini',
                                                    max_depth=None,
                                                    max_features=None,
                                                    max_leaf_nodes=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=2,
                                                    min_weight_fraction_leaf=0.0,
                                                    presort='deprecated',
                                                    random_state=42,
            

In [56]:
random_search.best_estimator_

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=120, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=42, splitter='best')

In [57]:
random_search.best_params_

{'criterion': 'gini', 'max_depth': 120, 'max_features': 'auto'}

In [58]:
random_search.best_score_

0.5609639701592065

In [59]:
y_pred = random_search.best_estimator_.predict(X_test)

In [61]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[101  68  84]
 [108 933 433]
 [ 84 457 732]]
              precision    recall  f1-score   support

           0       0.34      0.40      0.37       253
           1       0.64      0.63      0.64      1474
           2       0.59      0.58      0.58      1273

    accuracy                           0.59      3000
   macro avg       0.52      0.54      0.53      3000
weighted avg       0.59      0.59      0.59      3000



In [62]:
## apply cross validation

In [63]:
score = cross_val_score(DecisionTreeClassifier(criterion='gini', max_depth= 120, max_features='auto',random_state=42),X,y,cv=10)

In [64]:
score

array([0.68333333, 0.47      , 0.41066667, 0.428     , 0.42733333,
       0.43066667, 0.48066667, 0.93466667, 0.998     , 0.99799867])

In [65]:
score.mean()

0.6261331999110518

In [66]:
### lets apply gridsearchcv

In [70]:
max_depth = [int(i) for i in np.linspace(50,150,50)]
param_grid ={'criterion': 'gini', 
             'max_depth': max_depth, 
             'max_features': 'auto'}

In [71]:
grid_search = GridSearchCV(tree,param_grid=para_grid,cv=3).fit(X_train,y_train)

In [72]:
grid_search.best_score_

0.5609639701592065

In [73]:
grid_search.best_params_

{'criterion': 'gini', 'max_depth': 120, 'max_features': 'auto'}

In [ ]:
## same best parameter are came