##Import Libraries

In [59]:
import pandas as pd
import numpy as np

## Data load

In [61]:
df = pd.read_csv('/content/drive/My Drive/machine learning/classification/data/Human_Resources_Employee_Attrition.csv')
df.describe()

satisfaction_level  last_evaluation  ...          left  promotion_last_5years
count        14999.000000     14999.000000  ...  14999.000000           14999.000000
mean             0.612834         0.716102  ...      0.238083               0.021268
std              0.248631         0.171169  ...      0.425924               0.144281
min              0.090000         0.360000  ...      0.000000               0.000000
25%              0.440000         0.560000  ...      0.000000               0.000000
50%              0.640000         0.720000  ...      0.000000               0.000000
75%              0.820000         0.870000  ...      0.000000               0.000000
max              1.000000         1.000000  ...      1.000000               1.000000

[8 rows x 8 columns]

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   satisfaction_level     14999 non-null  float64
 1   last_evaluation        14999 non-null  float64
 2   number_of_projects     14999 non-null  int64  
 3   average_monthly_hours  14999 non-null  int64  
 4   years_at_company       14999 non-null  int64  
 5   work_accident          14999 non-null  int64  
 6   left                   14999 non-null  int64  
 7   promotion_last_5years  14999 non-null  int64  
 8   department             14999 non-null  object 
 9   salary                 14999 non-null  object 
dtypes: float64(2), int64(6), object(2)
memory usage: 1.1+ MB


In [63]:
df.salary.unique()

array(['low', 'medium', 'high'], dtype=object)

In [64]:
df.salary.unique()

array(['low', 'medium', 'high'], dtype=object)

In [65]:
df.salary.value_counts(ascending=False)

low       7316
medium    6446
high      1237
Name: salary, dtype: int64

In [66]:
df.department.unique()

array(['sales', 'accounting', 'hr', 'technical', 'support', 'management',
       'IT', 'product_mng', 'marketing', 'RandD'], dtype=object)

In [67]:
df.department.value_counts()

sales          4140
technical      2720
support        2229
IT             1227
product_mng     902
marketing       858
RandD           787
accounting      767
hr              739
management      630
Name: department, dtype: int64

In [68]:
df1 = df.copy()

## we have to change the categorcial data  into num data

### LabelEncoder

In [69]:
# in the target column we apply Lablencoding
# feature column we use OneHotEncoding

In [70]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [71]:
df1.iloc[:,9] = encoder.fit_transform(df1.iloc[:,9])

In [72]:
df1.head()

satisfaction_level  last_evaluation  ...  department  salary
0                0.38             0.53  ...       sales       1
1                0.80             0.86  ...       sales       2
2                0.11             0.88  ...       sales       2
3                0.72             0.87  ...       sales       1
4                0.37             0.52  ...       sales       1

[5 rows x 10 columns]

In [73]:
df.head()

satisfaction_level  last_evaluation  ...  department  salary
0                0.38             0.53  ...       sales     low
1                0.80             0.86  ...       sales  medium
2                0.11             0.88  ...       sales  medium
3                0.72             0.87  ...       sales     low
4                0.37             0.52  ...       sales     low

[5 rows x 10 columns]

In [74]:
df1.salary.unique()

array([1, 2, 0])

In [75]:
encoder.classes_
# high 0 ,low 1 ,medium 2

array(['high', 'low', 'medium'], dtype=object)

In [76]:
df.shape

(14999, 10)

###OneHotEncoding

In [77]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(dtype='int64')

In [78]:
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers = [('encoding',onehotencoder,[8])],remainder = 'passthrough')

In [79]:
df2 = ct.fit_transform(df1.iloc[:,:9])

In [80]:
df2.shape

(14999, 18)

In [81]:
df2.dtype

dtype('float64')

In [82]:
df2

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [83]:
df2[1]

array([  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   1.  ,
         0.  ,   0.  ,   0.8 ,   0.86,   5.  , 262.  ,   6.  ,   0.  ,
         1.  ,   0.  ])

In [84]:
df2 = pd.DataFrame(df2)

In [85]:

df2.head()

0    1    2    3    4    5    6   ...    11   12     13   14   15   16   17
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.53  2.0  157.0  3.0  0.0  1.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.86  5.0  262.0  6.0  0.0  1.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.88  7.0  272.0  4.0  0.0  1.0  0.0
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.87  5.0  223.0  5.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.52  2.0  159.0  3.0  0.0  1.0  0.0

[5 rows x 18 columns]

In [86]:
df2.head()

0    1    2    3    4    5    6   ...    11   12     13   14   15   16   17
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.53  2.0  157.0  3.0  0.0  1.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.86  5.0  262.0  6.0  0.0  1.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.88  7.0  272.0  4.0  0.0  1.0  0.0
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.87  5.0  223.0  5.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.52  2.0  159.0  3.0  0.0  1.0  0.0

[5 rows x 18 columns]

In [87]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       14999 non-null  float64
 1   1       14999 non-null  float64
 2   2       14999 non-null  float64
 3   3       14999 non-null  float64
 4   4       14999 non-null  float64
 5   5       14999 non-null  float64
 6   6       14999 non-null  float64
 7   7       14999 non-null  float64
 8   8       14999 non-null  float64
 9   9       14999 non-null  float64
 10  10      14999 non-null  float64
 11  11      14999 non-null  float64
 12  12      14999 non-null  float64
 13  13      14999 non-null  float64
 14  14      14999 non-null  float64
 15  15      14999 non-null  float64
 16  16      14999 non-null  float64
 17  17      14999 non-null  float64
dtypes: float64(18)
memory usage: 2.1 MB


## feature and target

In [88]:
X = df2.iloc[:,:-1].values
y = df1['salary'].values

In [89]:
X.shape,y.shape

((14999, 17), (14999,))

## scaling

In [90]:
from sklearn.preprocessing import StandardScaler
std =StandardScaler()
X = std.fit_transform(X)

## train test split data

In [91]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

##Model

In [92]:
from sklearn.ensemble import RandomForestClassifier

In [93]:
random_forest = RandomForestClassifier().fit(X_train,y_train)

In [94]:
y_pred = random_forest.predict(X_test)

In [110]:
random_forest.get_params

<bound method BaseEstimator.get_params of RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)>

In [95]:
from sklearn.metrics import confusion_matrix,classification_report

In [96]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[  84   86   83]
 [  16 1006  452]
 [  18  497  758]]
              precision    recall  f1-score   support

           0       0.71      0.33      0.45       253
           1       0.63      0.68      0.66      1474
           2       0.59      0.60      0.59      1273

    accuracy                           0.62      3000
   macro avg       0.64      0.54      0.57      3000
weighted avg       0.62      0.62      0.61      3000



In [97]:
## use cross validation 
##cv value change 

In [98]:
from sklearn.model_selection import cross_val_score
score = cross_val_score(random_forest,X,y,cv= 5)

In [99]:
score

array([0.584     , 0.45433333, 0.457     , 0.72533333, 0.96532177])

In [100]:
score.mean()

0.6371976881182617

## hyperparameter tuning

In [104]:
n_estimators = [int(i) for i in np.linspace(100,1000,10)]
criterion = ['gini','entropy']
max_depth = [int(i) for i in np.linspace(100,1000,10)]
max_features = ['auto', 'sqrt','log2']
min_samples_split = [2, 5, 10,14]
min_samples_leaf = [1, 2, 4,6,8]


In [105]:
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
              'criterion':['entropy','gini']}
random_grid

{'criterion': ['entropy', 'gini'],
 'max_depth': [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000],
 'max_features': ['auto', 'sqrt', 'log2'],
 'min_samples_leaf': [1, 2, 4, 6, 8],
 'min_samples_split': [2, 5, 10, 14],
 'n_estimators': [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]}

In [106]:
from sklearn.model_selection import RandomizedSearchCV
rf=RandomForestClassifier()
rf_randomcv=RandomizedSearchCV(estimator=rf,param_distributions=random_grid,n_iter=100,cv=3,verbose=2,
                               random_state=100,)
### fit the randomized model
rf_randomcv.fit(X_train,y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits
[CV] n_estimators=100, min_samples_split=2, min_samples_leaf=2, max_features=sqrt, max_depth=1000, criterion=entropy 


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV]  n_estimators=100, min_samples_split=2, min_samples_leaf=2, max_features=sqrt, max_depth=1000, criterion=entropy, total=   1.5s
[CV] n_estimators=100, min_samples_split=2, min_samples_leaf=2, max_features=sqrt, max_depth=1000, criterion=entropy 


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    1.5s remaining:    0.0s


[CV]  n_estimators=100, min_samples_split=2, min_samples_leaf=2, max_features=sqrt, max_depth=1000, criterion=entropy, total=   1.5s
[CV] n_estimators=100, min_samples_split=2, min_samples_leaf=2, max_features=sqrt, max_depth=1000, criterion=entropy 
[CV]  n_estimators=100, min_samples_split=2, min_samples_leaf=2, max_features=sqrt, max_depth=1000, criterion=entropy, total=   1.5s
[CV] n_estimators=700, min_samples_split=5, min_samples_leaf=6, max_features=sqrt, max_depth=200, criterion=gini 
[CV]  n_estimators=700, min_samples_split=5, min_samples_leaf=6, max_features=sqrt, max_depth=200, criterion=gini, total=   6.3s
[CV] n_estimators=700, min_samples_split=5, min_samples_leaf=6, max_features=sqrt, max_depth=200, criterion=gini 
[CV]  n_estimators=700, min_samples_split=5, min_samples_leaf=6, max_features=sqrt, max_depth=200, criterion=gini, total=   6.3s
[CV] n_estimators=700, min_samples_split=5, min_samples_leaf=6, max_features=sqrt, max_depth=200, criterion=gini 
[CV]  n_estimato

[Parallel(n_jobs=1)]: Done 300 out of 300 | elapsed: 31.6min finished


RandomizedSearchCV(cv=3, error_score=nan,
                   estimator=RandomForestClassifier(bootstrap=True,
                                                    ccp_alpha=0.0,
                                                    class_weight=None,
                                                    criterion='gini',
                                                    max_depth=None,
                                                    max_features='auto',
                                                    max_leaf_nodes=None,
                                                    max_samples=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=2,
                                                    min_weight_fraction_leaf=0.0,
               

In [107]:
rf_randomcv.best_params_

{'criterion': 'gini',
 'max_depth': 800,
 'max_features': 'log2',
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 300}

In [108]:
y_pred = rf_randomcv.best_estimator_.predict(X_test)

In [109]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[  84   86   83]
 [  10 1008  456]
 [  12  503  758]]
              precision    recall  f1-score   support

           0       0.79      0.33      0.47       253
           1       0.63      0.68      0.66      1474
           2       0.58      0.60      0.59      1273

    accuracy                           0.62      3000
   macro avg       0.67      0.54      0.57      3000
weighted avg       0.62      0.62      0.61      3000

