## Import libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Load data in pandas frame

In [2]:
df = pd.read_csv('/content/drive/My Drive/machine learning/regression/data/housing.csv')
df.head()

longitude  latitude  ...  median_house_value  ocean_proximity
0    -122.23     37.88  ...            452600.0         NEAR BAY
1    -122.22     37.86  ...            358500.0         NEAR BAY
2    -122.24     37.85  ...            352100.0         NEAR BAY
3    -122.25     37.85  ...            341300.0         NEAR BAY
4    -122.25     37.85  ...            342200.0         NEAR BAY

[5 rows x 10 columns]

## Prepaire the Data for Train the Model

In [3]:
df.ocean_proximity.unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [4]:
df = df.drop(columns=['longitude','latitude'])

In [5]:
df.head()

housing_median_age  total_rooms  ...  median_house_value  ocean_proximity
0                41.0        880.0  ...            452600.0         NEAR BAY
1                21.0       7099.0  ...            358500.0         NEAR BAY
2                52.0       1467.0  ...            352100.0         NEAR BAY
3                52.0       1274.0  ...            341300.0         NEAR BAY
4                52.0       1627.0  ...            342200.0         NEAR BAY

[5 rows x 8 columns]

In [6]:
df.isnull().sum()

housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [7]:
df = df.dropna()

In [8]:
df.isnull().sum()

housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20433 entries, 0 to 20639
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   housing_median_age  20433 non-null  float64
 1   total_rooms         20433 non-null  float64
 2   total_bedrooms      20433 non-null  float64
 3   population          20433 non-null  float64
 4   households          20433 non-null  float64
 5   median_income       20433 non-null  float64
 6   median_house_value  20433 non-null  float64
 7   ocean_proximity     20433 non-null  object 
dtypes: float64(7), object(1)
memory usage: 1.4+ MB


## Feature or Target values

In [10]:
X = df.drop(columns=['median_house_value']).values
y = df['median_house_value'].values

In [11]:
X

array([[41.0, 880.0, 129.0, ..., 126.0, 8.3252, 'NEAR BAY'],
       [21.0, 7099.0, 1106.0, ..., 1138.0, 8.3014, 'NEAR BAY'],
       [52.0, 1467.0, 190.0, ..., 177.0, 7.2574, 'NEAR BAY'],
       ...,
       [17.0, 2254.0, 485.0, ..., 433.0, 1.7, 'INLAND'],
       [18.0, 1860.0, 409.0, ..., 349.0, 1.8672, 'INLAND'],
       [16.0, 2785.0, 616.0, ..., 530.0, 2.3886, 'INLAND']], dtype=object)

## encoding

In [12]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import  ColumnTransformer

In [13]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[6])],remainder='passthrough')

X = ct.fit_transform(X)

In [14]:
X

array([[0.0, 0.0, 0.0, ..., 322.0, 126.0, 8.3252],
       [0.0, 0.0, 0.0, ..., 2401.0, 1138.0, 8.3014],
       [0.0, 0.0, 0.0, ..., 496.0, 177.0, 7.2574],
       ...,
       [0.0, 1.0, 0.0, ..., 1007.0, 433.0, 1.7],
       [0.0, 1.0, 0.0, ..., 741.0, 349.0, 1.8672],
       [0.0, 1.0, 0.0, ..., 1387.0, 530.0, 2.3886]], dtype=object)

In [15]:
y

array([452600., 358500., 352100., ...,  92300.,  84700.,  89400.])

## Train or test split the Data

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [17]:
X_train.shape,X_test.shape

((16346, 11), (4087, 11))

## Train model