# this is with  scalar data prediction

## Import libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Load data in pandas frame

In [ ]:
df = pd.read_csv('/content/drive/My Drive/machine learning/regression/data/housing.csv')
df.head()

longitude  latitude  ...  median_house_value  ocean_proximity
0    -122.23     37.88  ...            452600.0         NEAR BAY
1    -122.22     37.86  ...            358500.0         NEAR BAY
2    -122.24     37.85  ...            352100.0         NEAR BAY
3    -122.25     37.85  ...            341300.0         NEAR BAY
4    -122.25     37.85  ...            342200.0         NEAR BAY

[5 rows x 10 columns]

## Prepaire the Data for Train the Model

In [ ]:
df.ocean_proximity.unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [ ]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

here we can see that data is missing

so drop or fill with median value

In [ ]:
df = df.dropna()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20433 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20433 non-null  float64
 1   latitude            20433 non-null  float64
 2   housing_median_age  20433 non-null  float64
 3   total_rooms         20433 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20433 non-null  float64
 6   households          20433 non-null  float64
 7   median_income       20433 non-null  float64
 8   median_house_value  20433 non-null  float64
 9   ocean_proximity     20433 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.7+ MB


In [ ]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

## we are using encoding for ocean_proximity

In [ ]:
df1= df.loc[:,:].values

In [ ]:
df1

array([[-122.23, 37.88, 41.0, ..., 8.3252, 452600.0, 'NEAR BAY'],
       [-122.22, 37.86, 21.0, ..., 8.3014, 358500.0, 'NEAR BAY'],
       [-122.24, 37.85, 52.0, ..., 7.2574, 352100.0, 'NEAR BAY'],
       ...,
       [-121.22, 39.43, 17.0, ..., 1.7, 92300.0, 'INLAND'],
       [-121.32, 39.43, 18.0, ..., 1.8672, 84700.0, 'INLAND'],
       [-121.24, 39.37, 16.0, ..., 2.3886, 89400.0, 'INLAND']],
      dtype=object)

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import  ColumnTransformer

In [ ]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[9])],remainder='passthrough')

In [ ]:
df1 = ct.fit_transform(df1)

In [ ]:
ct.named_transformers_

{'encoder': OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
               handle_unknown='error', sparse=True),
 'remainder': 'passthrough'}

In [ ]:
ct.get_feature_names

<bound method ColumnTransformer.get_feature_names of ColumnTransformer(n_jobs=None, remainder='passthrough', sparse_threshold=0.3,
                  transformer_weights=None,
                  transformers=[('encoder',
                                 OneHotEncoder(categories='auto', drop=None,
                                               dtype=<class 'numpy.float64'>,
                                               handle_unknown='error',
                                               sparse=True),
                                 [9])],
                  verbose=False)>

## feature or target

In [ ]:
df2 = pd.DataFrame(df1)

In [ ]:
df2

0  1  2  3  4       5      6   7     8     9    10    11      12      13
0      0  0  0  1  0 -122.23  37.88  41   880   129   322   126  8.3252  452600
1      0  0  0  1  0 -122.22  37.86  21  7099  1106  2401  1138  8.3014  358500
2      0  0  0  1  0 -122.24  37.85  52  1467   190   496   177  7.2574  352100
3      0  0  0  1  0 -122.25  37.85  52  1274   235   558   219  5.6431  341300
4      0  0  0  1  0 -122.25  37.85  52  1627   280   565   259  3.8462  342200
...   .. .. .. .. ..     ...    ...  ..   ...   ...   ...   ...     ...     ...
20428  0  1  0  0  0 -121.09  39.48  25  1665   374   845   330  1.5603   78100
20429  0  1  0  0  0 -121.21  39.49  18   697   150   356   114  2.5568   77100
20430  0  1  0  0  0 -121.22  39.43  17  2254   485  1007   433     1.7   92300
20431  0  1  0  0  0 -121.32  39.43  18  1860   409   741   349  1.8672   84700
20432  0  1  0  0  0 -121.24  39.37  16  2785   616  1387   530  2.3886   89400

[20433 rows x 14 columns]

In [ ]:
X = df2.iloc[:,:-1].values
y = df2.iloc[:,-1].values

In [ ]:
X

array([[0.0, 0.0, 0.0, ..., 322.0, 126.0, 8.3252],
       [0.0, 0.0, 0.0, ..., 2401.0, 1138.0, 8.3014],
       [0.0, 0.0, 0.0, ..., 496.0, 177.0, 7.2574],
       ...,
       [0.0, 1.0, 0.0, ..., 1007.0, 433.0, 1.7],
       [0.0, 1.0, 0.0, ..., 741.0, 349.0, 1.8672],
       [0.0, 1.0, 0.0, ..., 1387.0, 530.0, 2.3886]], dtype=object)

In [ ]:
y.shape

(20433,)

## Train or test split the Data

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [ ]:
X_train.shape

(16346, 13)

In [ ]:
X_test.shape

(4087, 13)

In [ ]:
y_test.shape

(4087,)

##Scale the data

In [ ]:
from sklearn.preprocessing import StandardScaler
std =StandardScaler()

In [ ]:
X_train = std.fit_transform(X_train)
X_test = std.transform(X_test)

## Lets train train the model without standard scalar 

In [ ]:
from sklearn.linear_model import LinearRegression
linear_reg = LinearRegression()

In [ ]:
linear_reg.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
y_pred = linear_reg.predict(X_test)
np.set_printoptions(precision=2)

In [ ]:
y_pred.shape

(4087,)

Lets compare the values y perdictt or y test

In [ ]:
np.set_printoptions(precision=2)
print(np.concatenate((y_test.reshape(-1,1),y_pred.reshape(-1,1)),axis=1))

[[245800.0 202037.91564503743]
 [137900.0 147153.85750394405]
 [218200.0 207917.01368859637]
 ...
 [100200.0 110079.58219438662]
 [127700.0 137148.1730859853]
 [133700.0 169271.77854239696]]


In [ ]:
from sklearn.metrics import  mean_absolute_error,mean_squared_error,r2_score

In [ ]:
print(r2_score(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.648851550981854
4802018523.06375
50419.25735182429


## Now we are apply Lasso Regression

In [ ]:
from sklearn.linear_model import Lasso,Ridge,ElasticNet

In [ ]:
lasso_reg = Lasso(alpha=1.0)
lasso_reg.fit(X_train,y_train)
y_pred = lasso_reg.predict(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 2463844447809.211, tolerance: 21637001496.19773
  positive)


Now we check the model


1.   Score
2.   Mean Square error
3.   Mean Absolute error




In [ ]:
print(r2_score(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.6488389491882094
4802190854.870068
50413.317343980125


here we can see that model mean absolute error decrease

In [ ]:
lasso_reg = Lasso(alpha=5.0)
lasso_reg.fit(X_train,y_train)
y_pred = lasso_reg.predict(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 2469215022040.5234, tolerance: 21637001496.19773
  positive)


In [ ]:
print(r2_score(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.6488337368974473
4802262133.888549
50412.85348749922


In [ ]:
lasso_reg = Lasso(alpha=100)
lasso_reg.fit(X_train,y_train)
y_pred = lasso_reg.predict(X_test)

In [ ]:
print(r2_score(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.6487330920784975
4803638469.982868
50404.230192653675


In [ ]:
lasso_reg = Lasso(alpha=200)
lasso_reg.fit(X_train,y_train)
y_pred = lasso_reg.predict(X_test)

In [ ]:
print(r2_score(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.6484657895354451
4807293880.58368
50407.635038929824


as we can see that we minimize the error

## Ridge Regression

In [ ]:
ridge_reg = Ridge(alpha=1.0)
ridge_reg.fit(X_train,y_train)
y_pred = ridge_reg.predict(X_test)

In [ ]:
print(r2_score(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.6488397211423823
4802180298.257195
50412.41960463236


In [ ]:
ridge_reg = Ridge(alpha=10)
ridge_reg.fit(X_train,y_train)
y_pred = ridge_reg.predict(X_test)

In [ ]:
print(r2_score(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.6488275675899484
4802346500.28392
50404.484589106025


In [ ]:
ridge_reg = Ridge(alpha=100)
ridge_reg.fit(X_train,y_train)
y_pred = ridge_reg.predict(X_test)

In [ ]:
print(r2_score(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.6481946108577681
4811002298.026234
50389.4124660997


In [ ]:
ridge_reg = Ridge(alpha=11)
ridge_reg.fit(X_train,y_train)
y_pred = ridge_reg.predict(X_test)

In [ ]:
print(r2_score(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.6488254032891254
4802376097.488953
50403.73383339349


## Elastic net 

In [ ]:
elastic_reg = ElasticNet(alpha=1.0)
elastic_reg.fit(X_train,y_train)
y_pred = elastic_reg.predict(X_test)

Now we check the model


1.   Score
2.   Mean Square error
3.   Mean Absolute error




In [ ]:
print(r2_score(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.5667919190998537
5924198824.28671
57761.68490002713


In [ ]:
elastic_reg = ElasticNet(alpha=0.0005)
elastic_reg.fit(X_train,y_train)
y_pred = elastic_reg.predict(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 38334105110700.51, tolerance: 21637001496.19773
  positive)


In [ ]:
print(r2_score(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.6488369705993451
4802217912.43049
50409.42426520694


In [ ]:
elastic_reg = ElasticNet(alpha=10.0)
elastic_reg.fit(X_train,y_train)
y_pred = elastic_reg.predict(X_test)

In [ ]:
print(r2_score(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.23567676453264608
10452258423.99373
80703.06676654385


In [ ]:
elastic_reg = ElasticNet(alpha=0.00000006)
elastic_reg.fit(X_train,y_train)
y_pred = elastic_reg.predict(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 38315048747658.266, tolerance: 21637001496.19773
  positive)


In [ ]:
print(r2_score(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.6488402152220119
4802173541.628938
50413.432810923754
