## Import Libraries that we need 

In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Data load

In [28]:
df = pd.read_csv('/content/drive/My Drive/machine learning/regression/data/weight_age.csv')
df.head()

Id  Height  Age  Weight
0   1     122   43    40.0
1   2     132   42    42.0
2   3     155   41    49.0
3   4     215   40    70.0
4   5     150   49    50.0

height and age are feature column and tagert column is weight                     
before doing this we are check data is not missing 

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Id      10 non-null     int64  
 1   Height  10 non-null     int64  
 2   Age     10 non-null     int64  
 3   Weight  9 non-null      float64
dtypes: float64(1), int64(3)
memory usage: 448.0 bytes


weight column is missing value                                                             
we are going to mean value place where data is missing

In [30]:
df = df.fillna(df.mean())

or we fill by using sklearn SimpleImputer

In [31]:
X = df.iloc[:,1:-1].values
y = df.iloc[:,-1].values

In [32]:
print(X)

[[122  43]
 [132  42]
 [155  41]
 [215  40]
 [150  49]
 [165  46]
 [172  45]
 [133  49]
 [136  45]
 [155  40]]


In [33]:
y

array([40.        , 42.        , 49.        , 70.        , 50.        ,
       55.        , 60.        , 49.        , 50.        , 51.66666667])

##Train test split of data

In [34]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size =0.2,random_state =42)

model train 

In [35]:
from sklearn.linear_model import LinearRegression
linear_reg = LinearRegression()

train the model

In [36]:
linear_reg.fit(X_train,y_train)
linear_reg.score(X_test,y_test)

0.4436898647692612

Here we see the score of the model

we are use the standarization in the data or minmaxscalar

In [24]:
from sklearn.preprocessing import StandardScaler
std = StandardScaler()
X_train = std.fit_transform(X_train)
X_test = std.transform(X_test)

In [38]:
from sklearn.preprocessing import MinMaxScaler
scalar = MinMaxScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

In [39]:
X_train

array([[0.46236559, 0.66666667],
       [0.        , 0.33333333],
       [0.11827957, 1.        ],
       [0.35483871, 0.11111111],
       [0.35483871, 0.        ],
       [0.30107527, 1.        ],
       [1.        , 0.        ],
       [0.53763441, 0.55555556]])

In [40]:
linear_reg.fit(X_train,y_train)
linear_reg.score(X_test,y_test)

0.44368986476926164